Implementation of 50 methods or attribute codes.

In [9]:
# array
import numpy as np
a = np.array([2,3,4])
print(a)

[2 3 4]


In [10]:
# arrange
a=np.arange(3,7,2)
print(a)

[3 5]


In [67]:
# linspace
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [15]:
# copy
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
print(z)

[1 2 3]


In [16]:
#empty
np.empty([2, 2])

array([[0., 0.],
       [0., 0.]])

In [17]:
#empty_like
a = ([1,2,3], [4,5,6])                         # a is array-like
np.empty_like(a)

array([[-669015760,        552,          0],
       [         0,          1, 1968991539]])

In [18]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
#ones_like
a= np.array([1, 2, 3])
np.ones_like(a)

array([1, 1, 1])

In [21]:
#eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# r_
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]


array([1, 2, 3, 0, 0, 4, 5, 6])

In [23]:
#ndarray.astype
x = np.array([1, 2, 2.5])
x.astype(int)

array([1, 2, 2])

In [24]:
#atleast_1d
np.atleast_1d(1.0)

array([1.])

In [25]:
#atleast_2d
np.atleast_2d(3.0)

array([[3.]])

In [26]:
#atleast_3d
np.atleast_3d(3.0)

array([[[3.]]])

In [29]:
# asmatrix
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

In [30]:
# array_split
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [31]:
# column_stack
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [32]:
# concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
# diagonal
a = np.arange(4).reshape(2,2)
a.diagonal()

array([0, 3])

In [34]:
# dsplit
x = np.arange(16.0).reshape(2, 2, 4)
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [35]:
# dstack
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [36]:
# hsplit
x = np.arange(16.0).reshape(4, 4)
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [37]:
# hstack
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [38]:
# ndarray.item
x = np.random.randint(9, size=(3, 3))
x.item(3)

1

In [39]:
# ravel
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [40]:
# repeat
np.repeat(3, 4)

array([3, 3, 3, 3])

In [41]:
# all
np.all([[True,False],[True,True]])

False

In [42]:
# any
np.any([[True, False], [True, True]])

True

In [43]:
# nonzero
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [44]:
# where
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [45]:
# argmax
a = np.array([[10, 11, 12],[13, 14, 15]])
np.argmax(a)

5

In [46]:
# argmin
a = np.array([[10, 11, 12],[13, 14, 15]])
np.argmin(a)

0

In [47]:
#argsort
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [48]:
# ptp
x = np.array([[4, 9, 2, 10],[6, 9, 7, 12]])
np.ptp(x, axis=1)

array([8, 6])

In [49]:
# sort
a = np.array([[1,4],[3,1]])
np.sort(a) 

array([[1, 4],
       [1, 3]])

In [50]:
# searchsorted
np.searchsorted([1,2,3,4,5], 3)

2

In [51]:
# cov
x = np.array([[0, 2], [1, 1], [2, 0]]).T
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

In [52]:
# mean
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [53]:
# std
a = np.array([[1, 2], [3, 4]])
np.std(a)

1.118033988749895

In [54]:
# var
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

In [55]:
# cross
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [56]:
# dot
np.dot(3, 4)

12

In [59]:
# outer
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [60]:
#vdot
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

In [61]:
# sum
np.sum([0.5, 1.5])

2.0

In [62]:
#real
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [63]:
# putmask
x = np.arange(6).reshape(2, 3)
np.putmask(x, x>2, x**2)
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [64]:
# put
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [65]:
# prod
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)

16

In [66]:
# imag
a = np.array([1+2j, 3+4j, 5+6j])
a.imag

array([2., 4., 6.])